name: ci_pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
  steps:
    - name: Code
      uses: actions/checkout@v5

    - name: Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16
    
    - name: Dependencies
      run: npm install
    
    - name: Tests
      run: npm test